epilepticapi/urls.py
from django.urls import path

from .views import CheckFilesView

app_name = 'api'
urlpatterns = [
    path('check_files', CheckFilesView.as_view(), name='check_files'),
]

epilepticsearch/urls.py
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from epilepticsearch import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('epilepticapi.urls')),
    path('', include('frontend.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = 'frontend'
urlpatterns = [
    path('', TemplateView.as_view(template_name='frontend/index.html'), name='index'),
]

epilepticapi/models.py
from django.db import models

# Create your models here.

frontend/models.py
from django.db import models

# Create your models here.

epilepticapi/views.py
import pickle

from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from epilepticapi.ml.grad_img_generator import get_feature_and_grad_images_paths
from .utils import fail_json_response, save_report
from epilepticapi.ml.prediction import get_prediction_for_file
from epilepticsearch import settings

import time

class CheckFilesView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(CheckFilesView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        # Get files from form
        file_objects = request.FILES.getlist('document-files')
        # If file list is empty return error
        if not any(file_objects):
            return fail_json_response(error_code="NO_FILES_PRESENT")

        results = []
        for file_object in file_objects:
            file_result = {}
            file_result['file_name'] = file_object.name
            file_content = pickle.load(file_object.file)
            predictions = get_prediction_for_file(file_content, model_type='mean', use_cuda=False)
            feature_img_name, grad_img_name = get_feature_and_grad_images_paths(file_content, model_type='mean', use_cuda=False)

            feature_img_url = settings.MEDIA_URL + 'img/' + feature_img_name
            grad_img_url = settings.MEDIA_URL + 'img/' + grad_img_name

            types_predictions = {}
            for index, prediction in enumerate(predictions):
                type_prediction = {
                    "name": settings.LABEL_MAPPING_INV.get(index),
                    "probability": prediction
                }
                types_predictions["type_{}".format(index)] = type_prediction

            file_result['types'] = types_predictions
            file_result['class'] = predictions.index(max(predictions))
            file_result['feat_img_url'] = feature_img_url
            file_result['grad_img_url'] = grad_img_url
            results.append(file_result)

        # Generate report file
        report_file_name = save_report(results)
        report_file_url = settings.MEDIA_URL + 'reports/' + report_file_name

        response_result = {
            "success": True,
            "results": results,
            "report_url": report_file_url
        }
        return JsonResponse(data=response_result, safe=False)

frontend/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "assets/bootstrap-4.2.1/css/bootstrap.min.css" %}">

    <!-- Main CSS -->
    <link rel="stylesheet" href="{% static "css/main.css" %}">

    {% block styles %}{% endblock %}

    <title>DeepL{% block title %}{% endblock %}</title>
</head>
<body>

{% block body %}{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static "assets/jquery-3.3.1/jquery-3.3.1.min.js" %}"></script>
<script src="{% static "assets/bootstrap-4.2.1/js/bootstrap.bundle.min.js" %}"></script>
<!-- File upload -->
<script src="{% static "js/file-upload.js" %}"></script>

{% block scripts %}{% endblock %}
</body>
</html>

frontend/templates/frontend/error_modal.html
<div id="error-modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ошибка :(</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Ок</button>
      </div>
    </div>
  </div>
</div>

frontend/templates/frontend/index.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block body %}
    {% include 'nav.html' %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 pb-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            DeepL &mdash; нейронная сеть
                        </h5>
                        <p class="card-text">
                            Высокая точность определения вида эпилепсии.
                            Глубокая аналитика с вероятностями по каждому виду.
                        </p>
                        <p class="card-text">
                            Добавьте файлы с анализами в поле справа и получите аналитику по каждому файлу.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-5 offset-md-1 pb-2">
                <div class="card" style="height: 100%">
                    <div class="card-body">
                        <form method="post" action="{% url 'api:check_files' %}"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group image-upload-wrap">
                                <label for="file-input">Выберите файлы</label>
                                <input type="file" class="form-control-file" name="document-files" id="file-input"
                                       multiple>
                            </div>
                            <div class="form-group">
                                <button type="button" class="btn btn-primary" id="epileptic-search-upload">
                                    Отправить
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Результаты</h5>
                <a href="#" class="card-link" id="download-link">Скачать в CSV</a>
                <div class="row" id="epileptic-results" style="margin-top: 20px"></div>
            </div>
        </div>
    </div>

    {% include 'frontend/error_modal.html' %}
{% endblock %}

frontend/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4" style="height: 80px">
    <h2 style="position: absolute;
    color: white;
    width: 100%;
    left: 0;
    top: 20px;
    text-align: center;
    margin: auto;">
        DeepL. Deep epilepsy classification
    </h2>
</nav>